#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
source "${ROOT_DIR}/scripts/_minestudio_runtime.sh"

setup_minestudio_runtime
ensure_minestudio_engine

RUN_TAG="${RUN_TAG:-p_obstacle_maze_t6_control_vm_rebuild_$(date +%Y%m%d_%H%M%S)}"
OUT_ROOT="${OUT_ROOT:-${ROOT_DIR}/outputs/evaluate_rocket/${RUN_TAG}}"
ASSET_ROOT="${ASSET_ROOT:-${OUT_ROOT}/assets}"

PATH_PROGRESS_REWARD_PER_ZONE="${PATH_PROGRESS_REWARD_PER_ZONE:-0.125}"
BANK_WORKERS="${BANK_WORKERS:-4}"
COLLECT_WORKERS="${COLLECT_WORKERS:-4}"
VIDEO_WORKERS="${VIDEO_WORKERS:-4}"
EVAL_WORKERS="${EVAL_WORKERS:-4}"
FINAL_PROBE_WORKERS="${FINAL_PROBE_WORKERS:-4}"
STEP_BUDGET="${STEP_BUDGET:-150}"

RUN_VIDEO_PROBE="${RUN_VIDEO_PROBE:-1}"
RUN_BASELINE_EVAL="${RUN_BASELINE_EVAL:-1}"
RUN_CONTROL_A="${RUN_CONTROL_A:-1}"
RUN_MAIN_B="${RUN_MAIN_B:-0}"

RUN_TAG="${RUN_TAG}" \
OUT_ROOT="${OUT_ROOT}" \
ASSET_ROOT="${ASSET_ROOT}" \
ASSET_DIR="" \
RUN_VIDEO_PROBE="${RUN_VIDEO_PROBE}" \
RUN_BASELINE_EVAL="${RUN_BASELINE_EVAL}" \
RUN_CONTROL_A="${RUN_CONTROL_A}" \
RUN_MAIN_B="${RUN_MAIN_B}" \
STEP_BUDGET="${STEP_BUDGET}" \
PATH_PROGRESS_REWARD_PER_ZONE="${PATH_PROGRESS_REWARD_PER_ZONE}" \
BANK_WORKERS="${BANK_WORKERS}" \
COLLECT_WORKERS="${COLLECT_WORKERS}" \
VIDEO_WORKERS="${VIDEO_WORKERS}" \
EVAL_WORKERS="${EVAL_WORKERS}" \
FINAL_PROBE_WORKERS="${FINAL_PROBE_WORKERS}" \
bash "${ROOT_DIR}/scripts/run_p_obstacle_maze_t6_uniform_reward_suite.sh"
